name: Terraform Destroy

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to run the workflow."
        type: string
        required: true
      main-repo:
        description: main repository to be used
        required: true
        type: string
    
jobs:
  terraform:
    name: Terraform Destroy on ${{inputs.environment}} Environment
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Pull the repo changes done on the previous job
        run: git pull

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
